version: '3.4'
services:
  gms-banks:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /banks
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: test
    ports:
      - "8080:8080"
    volumes:
      - ./:/banks
      - ~/.m2:/root/.m2
    networks:
      - banks-network
networks:
    banks-network:
        driver: bridge